### ISSUE TITLE
Dependency `packaging` not specified — ModuleNotFoundError

### ISSUE THREAD

**Issue by lainisourgod** [catalyst-team/catalyst#1417]
## 🐛 Bug Report

Hi!

Catalyst uses dependency `packaging` [here](https://github.com/catalyst-team/catalyst/blob/master/catalyst/settings.py#L6) but does not specify it directly in any of dependency files.

When installing catalyst via poetry `poetry add catalyst`, `packaging` dependency isn't installed. This bug is silent most of the times because some other packages as `jupyter` install `packaging`, but in my env this bug there is none of these packages.

### How To Reproduce
1. `mkdir test-proj && cd test-proj` 
2. Create `pyproject.toml` with `catalyst` being the only dependency
```toml
[tool.poetry]
name = "test-proj"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.7"
catalyst = "^22.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```
3. Create `main.py`
```bash
mkdir test_proj && touch test_proj/main.py && cat "import catalyst" > test_proj/main.py
```
4. Get error message
```
❯ poetry run python test_proj/main.py 
Traceback (most recent call last):
  File "test_proj/main.py", line 1, in <module>
    import catalyst
  File "/home/user/.cache/pypoetry/virtualenvs/test_proj-vU8Qtjuj-py3.7/lib/python3.7/site-packages/catalyst/__init__.py", line 12, in <module>
    from catalyst.settings import SETTINGS
  File "/home/user/.cache/pypoetry/virtualenvs/test_proj-vU8Qtjuj-py3.7/lib/python3.7/site-packages/catalyst/settings.py", line 6, in <module>
    from packaging.version import Version
ModuleNotFoundError: No module named 'packaging'
```

### Environment
```
Catalyst version: 22.04
PyTorch version: 1.11.0+cu102
Python version: 3.7
```

### Checklist
- [ ] bug description
- [ ] steps to reproduce
- [ ] expected behavior
- [ ] environment
- [ ] code sample / screenshots
  
### FAQ
Please review the FAQ before submitting an issue:
- [ ] I have read the [documentation and FAQ](https://catalyst-team.github.io/catalyst/)
- [ ] I have reviewed the [minimal examples section](https://github.com/catalyst-team/catalyst#minimal-examples)
- [ ] I have checked the [changelog](https://github.com/catalyst-team/catalyst/blob/master/CHANGELOG.md) for main framework updates
- [ ] I have read the [contribution guide](https://github.com/catalyst-team/catalyst/blob/master/CONTRIBUTING.md)
- [ ] I have joined [Catalyst slack (#__questions channel)](https://join.slack.com/t/catalyst-team-core/shared_invite/zt-d9miirnn-z86oKDzFMKlMG4fgFdZafw) for issue discussion
