### ISSUE TITLE
OneCycle Scheduler bug

### ISSUE THREAD

**Issue by belskikh** [catalyst-team/catalyst#215]
There is a problem in OneCycle Scheduler parameters.
According to https://catalyst-team.github.io/catalyst/api/contrib.html#catalyst.contrib.scheduler.OneCycleLR it has parameters `lr_range` and `momentum_range`, that are tuples with max/min, min/max and final values.
But lr and momentum changes in the opposite way: lr decreases and momentum increases.
If I change parameters order, it works fine.

Working example:
```
  scheduler_params:
    scheduler: OneCycleLR
    num_steps: 10
    lr_range: [0.000001, 0.00002]
    init_lr: 0.000001
    momentum_range: [0.99, 0.8]
```
