### ISSUE TITLE
How to resume training from checkpoint?

### ISSUE THREAD

**Issue by bamps53** [catalyst-team/catalyst#366]
I found resume argument in predict_loader function, but not in train function. How can I resume from best checkpoint??

**Comment by ngxbac** [comment]
Very good question!. 
I think Catalyst hasnt supported it, is it? @Scitator 
I encountered this problem before. Here is my solution.

1. In the configure file (ex: config.yml), you should to add `resume` to the config:
```yml
args:
  expdir: "src"
  logdir: &logdir "logs"
  baselogdir: "logs"
  resume: #your checkpoint
``` 
2. Modify your `runner.py` 
```python

class ModelRunner(Runner):
    def predict_batch(self, batch: Mapping[str, Any]):
        output = self.model(batch["images"])
        return {
            "logits": output
        }

    def _run_stage(self, stage: str):
        self._prepare_state(stage)
        loaders = self.experiment.get_loaders(stage)
        self.callbacks = self.experiment.get_callbacks(stage)

        self._run_event("stage_start")
        for epoch in range(18, self.state.num_epochs):
            self.state.stage_epoch = epoch

            self._run_event("epoch_start")
            self._run_epoch(loaders)
            self._run_event("epoch_end")

            if self._check_run and self.state.epoch >= 3:
                break
            if self.state.early_stop:
                self.state.early_stop = False
                break

            self.state.epoch += 1
        self._run_event("stage_end")
```

In here, I resume from `epoch 18`.

**Comment by Scitator** [comment]
Hi,

Sorry for long answer – there are few conferences and competitions now :)

So, it's really good question... or even proposal.
For now, you can use workaround like (Notebook API)
```
from catalyst.dl import SupervisedRunner
from catalyst import utils

model = Net()
checkpoint = utils.load_checkpoint(resume=...)
utils.unpack_checkpoint(checkpoint, model=model)

runner = SupervisedRunner(model=model)
runner.train(...)
```

For config API, all you need to do is something like
```
callbacks_params:
      loader:
        callback: CheckpointCallback
        resume: <path/to/checkpoint.pth>
```
