### ISSUE TITLE
Exponential format for floats in experiment config

### ISSUE THREAD

**Issue by Dipet** [catalyst-team/catalyst#380]
At this time if I set some value in exponential format, like `lr: 1e-3` all this values transforms to strings.

**Comment by Scitator** [comment]
Could you please describe your proposal in more details?

**Comment by Dipet** [comment]
At this time I need write something like this
```
stage:
    state_params:
      optimizer_params:
        optimizer: Adam

        lr_linear_scaling:
          lr: 0.000005
        weight_decay: 0.00001
```

In exponential format I will can write like this:
```
stage:
    state_params:
      optimizer_params:
        optimizer: Adam

        lr_linear_scaling:
          lr: 5e-6
        weight_decay: 1e-5
```
